### ISSUE TITLE
UTF-8 display broken for markdown templates

### ISSUE THREAD

**Issue by sammakkoinen** [vanstyn/RapidApp#192]
In a fresh installation of RapidApp v1.3302 (tested in Perlbrew with perl 5.24.4) I am able to create the default dashboard template dashboard.md via the web editor, as suggested. However, if the file's text contains UTF-8 chars, they display double-encoded. Nevertheless, in the editor form the display is correct, and the file itself is saved correctly. To reproduce, in the web editor add words like "coöperation, Æons" to the text of dashboard.md and save. The result is displayed as "coÃ¶peration, Ãons".

So far I have noticed the removing this line: 
https://github.com/vanstyn/RapidApp/blob/585627c35cd6e530204a4bab73f69088f018fff5/lib/RapidApp/Template/Controller.pm#L550
fixes the issue, however I haven't checked for possible side effects thoroughly.

**Comment by tehmoth** [comment]
This also fixes the doubly encoded right angled quotes when editing pages in the RA infosite cms demo : https://github.com/IntelliTree/RA-InfoSite_cmsdemo
the doubly encoded right angle quotes appear to have affected the http://www.rapidapp.info/ website,
![image](https://user-images.githubusercontent.com/53626/102002364-d97ef000-3cc9-11eb-9edb-27e91373b623.png)

**Comment by vanstyn** [comment]
Thanks both of you for the feedback. I will make efforts to swing around to address this as soon as I can. I'm unfortunately very overcommitted at the moment. I know for a fact this worked properly before, so something else must have happened to cause this regression. If possible, if one of you could do a bisect to track down when this broke, that would be extremely helpful, and would speed up a fix getting shipped to CPAN. If the answer lies in changes to the CPAN stack (which is my gut) a bisect may not work. (or be prohibitively difficult. 

This is an import issue and I will address it regardless. Thanks again very much

**Comment by vanstyn** [comment]
See the comment in the commit I just made which closed the issue. I've removed that line since regardless of the story that is something that shouldn't be happen, and it was a duct-taped hack probably anyway just looking at the comment. So I don't think this could be worse. 

@sammakkoinen - this change will ship in the next CPAN release, please let me know if it solves your problem, and if not, re-open this

Something we still really need are test cases for template rendering.

**Comment by vanstyn** [comment]
shipped to CPAN in v1.3400

**Comment by sammakkoinen** [comment]
For the moment, everything has been working correctly with this version.

**Comment by sammakkoinen** [comment]
I seem to have found the underlying reason of the problem described here. See the Catalyst docs (https://metacpan.org/dist/Catalyst-Runtime/view/lib/Catalyst/UTF8.pod):

> 
>  Beginning with Catalyst version 5.90080 You no longer need to set the
>  encoding configuration (although doing so won't hurt anything).
> 
>  Currently we only encode if the content type is one of the types which
>  generally expects a UTF8 encoding. This is determined by the following
>  regular expression:
> 
>         our $DEFAULT_ENCODE_CONTENT_TYPE_MATCH = qr{text|xml$|javascript$};
>         $c->response->content_type =~ /$DEFAULT_ENCODE_CONTENT_TYPE_MATCH/

So text/javascript is automatically utf8-encoded by Catalyst, but application/json is not:

 

>    NOTE We do not attempt to encode "application/json" since the two most
>     commonly used approaches (Catalyst::View::JSON and
>     Catalyst::Action::REST) have already configured their JSON encoders to
>     produce properly encoding UTF8 responses. If you are rolling your own
>     JSON encoding, you may need to set the encoder to do the right thing (or
>     override the global regular expression to include the JSON media type).
> 
RapidApp was doing its own encoding in encode_json_utf8(), but for some reason JSON responses are sent with text/javascript content-type (in https://github.com/vanstyn/RapidApp/blob/53f3cc11a15877f624a75113be6b611f6d7bf901/lib/RapidApp/Template/Controller.pm#L472 and https://github.com/vanstyn/RapidApp/blob/53f3cc11a15877f624a75113be6b611f6d7bf901/lib/RapidApp/View/JSON.pm#L96). So the response gets encoded again by Catalyst as any text/javascript response, and the line https://github.com/vanstyn/RapidApp/blob/53f3cc11a15877f624a75113be6b611f6d7bf901/lib/RapidApp/Template/Controller.pm#L557 (uncommented) becomes necessary to decode it back. 

So I wonder why the response content-type is chosen to be text/javascript and not application/json?

(The switch to encode_json_ascii does fix it, but is not very suitable for my project, where I do a lot of JSON debugging, and JSON content gets unreadable. Maybe it could be a tunable setting, which function to use to encode?)

**Comment by nrdvana** [comment]
@sammakkoinen Strictly speaking, the data returned by RapidApp is JavaScript, because it often contains functions or date objects, so it really isn't "JSON".  This is the whole reason we have our own "json" encoding (and we really should have named those functions "encode_javascript" for clarity, but we subclassed the JSON::PP module and didn't think to change the name, at the time)  If we did return true JSON, we'd need the client-side to walk the data tree to inflate date objects and functions, which would be a fair-sized performance hit.

Encoding the non-ascii as javascript string escapes seemed like a good solution to us, but yes I can see that would be a pain if you're trying to read non-english text in the debugger.  We could probably do a content type of "application/javascript" to sidestep Catalyst's encoding.  I'm not sure if that would break anything.  If we use "application/json" ... I think it breaks because ExtJS attempts to automatically decode the data, but it's been a really long time since we chose the content-type.

If you find a solution that works for your projects, I'll test on some of ours.
